---

- include_tasks: tasks/repo/repo.{{ ansible_os_family }}.yml
- include_tasks: "tasks/{{ zabbix_function }}/install_zabbix_{{ zabbix_function }}.{{ ansible_os_family }}.yml"
- include_tasks: "tasks/{{ zabbix_function }}/config_zabbix_{{ zabbix_function }}.{{ ansible_os_family }}.yml"

- include_tasks: "tasks/{{ zabbix_function }}/userperm.yml"
  when: userperm is defined
