---

- include_tasks: tasks/repo/repo.{{ ansible_os_family }}.yml
  tags: 
    - repo    
    - agent.install
    - server.install
    - proxy.install

- include_tasks: "tasks/{{ zabbix_function }}/install_zabbix_{{ zabbix_function }}.{{ ansible_os_family }}.yml"
  tags: 
    - agent.install
    - server.install
    - proxy.install

- include_tasks: "tasks/{{ zabbix_function }}/config_zabbix_{{ zabbix_function }}.{{ ansible_os_family }}.yml"
  tags:    
    - proxy.install
    - server.install
    - proxy.config
    - server.config

- include_tasks: "tasks/{{ zabbix_function }}/zabbix_add_host.yml"
  tags:
    - agent.install
    - add.host

- include_tasks: "tasks/agent/userparam.yml"
  when : userparam is defined
  tags: 
    - userparam

- include_tasks: "tasks/{{ zabbix_function }}/external_script.yml"
  when: external_script is defined
  tags: externalScript

- include_tasks: tasks/server/zabbix-screens.yml
  when : zabbix_function == "server"
  tags: config.screen
