---

#########################################################################
- name: Get repo name for latest
  shell: "curl http://repo.zabbix.com/zabbix/{{ zabbix_version  }}/debian/pool/main/z/zabbix-release/ | grep '{{ ansible_distribution_release  }}*_all.deb' | cut -f6 -d '\"'"
  register: "{{ repo_name.stdout }}"

- set_fact:
     ansible_zabbix_repo: repo_name

# Debian settings
- name: Wget zabbix repo
  get_url:
    url: "http://repo.zabbix.com/zabbix/{{ zabbix_version  }}/debian/pool/main/z/zabbix-release/{{ ansible_zabbix_repo }}"
    dest: /tmp
#  when: {{  ansible_distribution  }} == 'debian'
  tags: 
    - repo

# Debian version - Check on linux distro before this task. Base it on fact ansible_distribution
- name: Install zabbix repo
  apt: 
    deb: "/tmp/{{ ansible_zabbix_repo }}"
    dpkg_options: 'post-invoke="apt-get -f install -y"'
#  when: {{  ansible_distribution  }} == 'debian'
  tags: repo

- name: Update packages repository
  apt:
    update_cache: yes
    cache_valid_time: 1800
#  when: {{  ansible_distribution  }} == 'debian'
  tags:
    - repo 

#######################################################################

# Distro REDHAT

# rpm -ivh http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/

#- name: Wget zabbix repo
##  shell: wget -r --no-parent -A 'zabbix-release-{{ zabbix_version }}-*.el7.noarch.rpm'  http://repo.zabbix.com/zabbix/{{ zabbix_version  }}/rhel/7/x86_64/
#    chdir: /tmp
#  when: "{{  ansible_distribution  }} == 'redhat'"
#  tags:
#    - repo
#
#- name: Install zabbix repo
 # shell: rpm -ivh repo.zabbix.com/zabbix/{{ zabbix_version  }}/rhel/7/x86_64/zabbix-release-{{ zabbix_version }}-*.el7.noarch.rpm
 #   chdir: /tmp
 # when: "{{  ansible_distribution  }} == 'redhat'"
 # tags: repo
