
Vagrant.configure("2") do |redhat|
  redhat.vm.define "zabbix-server" do |zabbix|
    zabbix.vm.box = "centos/7"
    zabbix.vm.hostname = "zabbix-server"
    zabbix.vm.network "private_network", ip: "192.168.77.201"
  end
  redhat.vm.define "zabbix-agent" do |zabbix_agent|
    zabbix_agent.vm.box = "centos/7"
    zabbix_agent.vm.hostname = "zabbix-agent"
    zabbix_agent.vm.network "private_network", ip: "192.168.77.202"
  end
  redhat.vm.define "zabbix-proxy" do |zabbix_proxy|
    zabbix_proxy.vm.box = "centos/7"
    zabbix_proxy.vm.hostname = "zabbix-proxy"
    zabbix_proxy.vm.network "private_network",ip: "192.168.77.203"
  end
  redhat.vm.provision "ansible" do |ansible|
    ansible.verbose = true
    ansible.playbook = "zabbix_prep.yml"
    ansible.host_vars = {
       	"zabbix-server" => {"zabbix_function" => "server","note" => "Zabbix server running CentOS"},
       	"zabbix-agent" => {"note" => "This is s figlet server running CentOS"},
       	"zabbix-proxy" => {"note" => "Running role - Zabbix Proxy server"}
      }
      ansible.groups = {
        "PRODUCTION" => ["zabbix-server", "zabbix-agent", "zabbix-proxy"],
        "ZABBIX_SERVER" => ["zabbix-server"],
        "ZABBIX_PROXIES" => ["zabbix-proxy"],
        "PRODUCTION:vars" => {
		"environ" => "PRE-PRODUCTION", 
		"warn" => "This is a pre-prod server - Think about what you are doing and BE CAREFULL",
		"zabbix_server" => "192.168.77.201",
		"zabbix_proxies" => ["192.168.77.203","192.168.121.134"],
	}
      }
  end
end
