---

- name: restart zabbix
  service: name={{ zabbix_service }} state=restarted enabled=yes

- name: restart webservice
  service: name={{ apache_service_RedHat }} state=restarted enabled=yes

- name: restart agent
  service: name=zabbix-agent state=restarted enabled=yes

- name: rebuild
  template: src=templates/zabbix_server.conf.j2 dest=/etc/zabbix/zabbix_server.conf
