---

- name: restart zabbix
  service: name={{ zabbix_service }} state=restarted enabled=yes

- name: restart webservice
  service: name={{ apache_service_RedHat }} state=restarted enabled=yes

- name: restart proxy
  service: name=zabbix-proxy state=restarted enabled=yes

- name: restart agent
  service: name=zabbix-agent state=restarted enabled=yes

- name: rebuild
  template: 
    src=templates/zabbix_{{ zabbix_function }}.conf.j2 dest=/etc/zabbix/zabbix_{{ zabbix_function }}.conf

- name: rebuild agent conf
  template: 
    src=templates/zabbix_agent.conf.j2 dest=/etc/zabbix/zabbix_agent.conf

