---

- name: Configure zabbix agent
  template: src=templates/zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf mode=0644
  tags: 
    - agent-config
    - agent-install
  notify: restart agent


