---

- name: Create zabbix_server.conf.d
  file: path=/etc/zabbix/zabbix_server.conf.d state=directory
  tags:
    - userparam

- name: Copy userperm script to server, remember to place in your script folder
  copy:
    src: "{{ userperm_dir }}/{{ item.script }}"
    dest: "/etc/zabbix/zabbix_server.conf.d/{{ item.name }}.conf"
    owner: zabbix
    group: zabbix
    mode: 0700
    backup: yes
    validate: grep '^UserParameter=*' %s 
  with_items:
    - "{{ userperm }}"
  tags:
    - userparam
