---

- name: install zabbix server
  apt: pkg="{{ item }}" state=present
  with_items:
    - "zabbix-server-{{ db_backend }}" 
    - zabbix-frontend-php
  tags:
    - install

- name: Restore database
  mysql_db: name=zabbix login_user=zabbix_service login_password=pass_zabbix state=import target=/usr/share/doc/zabbix-server-{{ db_backend }}/create.sql.gz
#  with_items:
#    - schema.sql.gz
#    - images.sql.gz
#    - data.sql.gz 

- name: Start zabbix-server service
  service: name={{ zabbix_service  }} state=restarted enabled=yes

