---

# see link for documentation - https://docs.ansible.com/ansible/2.5/modules/zabbix_screen_module.html?highlight=zabbix
- debug:
    msg: "{{ item }}"
  with_items:
    - "{{ config_screens }}"
  tags: config.screen

- name: Create a new screen or update an existing screen's items
  local_action:
    module: zabbix_screen
    server_url: "http://{{zabbix_server }}/zabbix"
    login_user: "{{ item.admin }}"
    login_password: "{{ item.pass }}"
    screens:
      - screen_name: "{{ item.screen_name }}"
        host_group: "{{ item.host_group }}"
        state: present
        graph_names: "{{ item.graph }}" 
        graph_width: "{{ item.width | default(graph_width) }}"
        graph_height: "{{ item.width | default(graph_height) }}"
  with_items:
    - "{{ config_screens }}"
  become: false
  tags: 
    - config.screen
