---

- name: Get repo name for latest
  get_url: url="http://repo.zabbix.com/zabbix/{{ zabbix_version  }}/rhel/7/x86_64/" dest=/tmp
  changed_when: false
  tags:
    - repo    
    - agent.install
    - server.install
    - proxy.install


- name: Cleaning repo file
  shell: "grep zabbix-release /tmp/index.html | tail -n 1 | cut -f2 -d '>' | cut -f1 -d '<'"
  register: repo_name
  changed_when: false
  tags: 
    - repo
    - agent.install
    - server.install
    - proxy.install
    
- name: Get latest Redhat zabbix repo
  get_url:
    url: "http://repo.zabbix.com/zabbix/{{ zabbix_version  }}/rhel/7/x86_64/{{ repo_name.stdout }}"
    dest: /tmp
  tags: 
    - repo
    - agent.install
    - server.install
    - proxy.install

- name: install zabbix rpm from a local file
  yum:
    name: "/tmp/{{ repo_name.stdout }}"
    state: present
  tags:
    - repo
    - agent.install
    - server.install
    - proxy.install